### ISSUE TITLE
Turbulence kills the wrong index, sometimes.

### ISSUE THREAD

**Issue by ghost** [cppforlife/turbulence-release#1]
this stuff is broken

https://github.com/cppforlife/turbulence-release/blob/1e1e0449609bcb49eaa10d9a5e0492b75e41415d/src/github.com/cppforlife/turbulence/incident/incident.go#L95-L108

**Comment by cppforlife** [comment]
Fixed in https://github.com/cppforlife/turbulence-release/commit/f68fdf37e3250cb0c77f490ea13a18a81d28744b.
