### ISSUE TITLE
Can't update submodules

### ISSUE THREAD

**Issue by benmoss** [cppforlife/turbulence-release#10]
When you clone this repo and run `git submodule update`, it fails with `fatal: No url found for submodule path 'src/github.com/onsi/ginkgo' in .gitmodules`

We are trying to submodule this release in our repo, and so when we recursively clone this project it fails. It looks like you need to commit the `.gitmodules` file.

**Comment by cppforlife** [comment]
there is no submodules in this repo, hence git submodule update isnt required.

**Comment by ekcasey** [comment]
When we submodule turbulence-release into our repo this issue prevents us from recursively updating submodules in our repo.

**Comment by benmoss** [comment]
git submodules are marked with the file mode `160000` (https://longair.net/blog/2010/06/02/git-submodules-explained/)

```
$ git ls-files --stage | grep 160000
160000 d94e2f4000332f62b356ecb2840c98f4218f5358 0	src/github.com/onsi/ginkgo
160000 a83829b6f1293c91addabc89d0571c246397bbf4 0	src/gopkg.in/yaml.v2
```

**Comment by benmoss** [comment]
ill send a pr to fix these

**Comment by cppforlife** [comment]
@benmoss looks like somehow they ended up there. removed them.
