### ISSUE TITLE
Turbulence can not be authorized on BOSH director

### ISSUE THREAD

**Issue by allomov** [cppforlife/turbulence-release#11]
Hey, @cppforlife.

I am trying to run turbulence (v0.5) with BOSH (v1.3262.3) that has authentication through UAA with CA cert. I provided all necessary data during BOSH deployment:
```
bosh -n -d turbulence deploy ./manifests/turbulence.yml \
  -v turbulence_api_ip=$TURBULENCE_API_IP \
  -v director_ip=$DIRECTOR_IP \
  --var-file director_ssl_ca=$DIRECTOR_SSL_CA \
  -v director_client=$DIRECTOR_CLIENT \
  -v director_client_secret=$DIRECTOR_CLIENT_SECRET \
  --vars-store ./creds.yml
```
When I try to run "kill" incident I get following error: 
```
Failed to execute incident: Finding deployments: Director responded with non-successful status code '401' response 'Not authorized: '/deployments'
```
You can find [here](https://gist.github.com/allomov/d385273ebbc129df7f1a365d2ef9b08d) logs with more details. With the same values I can login to director using golang bosh-cli. I've create a simple [go script to reproduce](https://gist.github.com/allomov/acb3974248ab7219ecab5a71d6e678d0) this problem.

Could you please tell what I possibly do wrong? Thank you.

**Comment by cppforlife** [comment]
@allomov are you using uaa auth? or regular?

**Comment by allomov** [comment]
uaa auth

**Comment by cppforlife** [comment]
@allomov are you sure that you have configured properly client and its secret? can you try using cli v2 like this: `bosh -e foo --client $DIRECTOR_CLIENT --client-secret $DIRECTOR_CLIENT_SECRET deps`.

**Comment by allomov** [comment]
The command runs without errors.

**Comment by allomov** [comment]
Right now I've noticed that turbulence VM has a failing state and I found following error in `/var/vcap/sys/log/turbulence_api/stderr.log`:
```
********************
[director.Factory] 2017/01/31 18:20:43 DEBUG - Using custom root CAs
[httpClient] 2017/01/31 18:20:43 DEBUG - Sending GET request to endpoint 'https://10.165.115.5:25555/info'
[main] 2017/01/31 18:20:43 ERROR - Failed building director: Fetching info: Performing request GET 'https://10.165.115.5:25555/info': Performing GET request: Get https://10.165.115.5:25555/info: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "serial:1")
```
Wondering why it tries to validate certificates with BOSH, and why they are failing. I guess we need rootCA.pem only to connect to UAA, not BOSH director. Will run some curl tests.

**Comment by allomov** [comment]
Never mind, the problem was in wrong root CA cert. Looks like I deployed it cert from another env.

**Comment by allomov** [comment]
The problem with BOSH Director authentication still exist: when I run 
```
body=...
echo $body | curl -vvv -k -X POST https://turbulence:${TURBULENCE_API_PASSWORD}@$TURBULENCE_API_IP:8080/api/v1/incidents -H 'Accept: application/json' -d @-
```
I get failed accident in in a turbulence web console with following error message: `Finding deployments: Director responded with non-successful status code '401' response 'Not authorized: '/deployments'
'`. I can ssh to turbulence VM and run following commands:
```

export CONFIG_FILE=/var/vcap/jobs/turbulence_api/config/config.json
export BOSH_HOST=$(cat $CONFIG_FILE | jq -r .Director.Host)
export BOSH_CLIENT=$(cat $CONFIG_FILE | jq -r .Director.Client)
export BOSH_CLIENT_SECRET=$(cat $CONFIG_FILE | jq -r .Director.ClientSecret)

export BOSH_CA_CERT=/root/boshUaaCA.pem
cat $CONFIG_FILE | jq -r .Director.CACert > $BOSH_CA_CERT


UAA_TOKEN=$(curl --cacert $BOSH_CA_CERT -v -X POST --data "grant_type=client_credentials&client_id=$BOSH_CLIENT&client_secret=$BOSH_CLIENT_SECRET" "https://$BOSH_HOST:8443/oauth/token" | jq -r .access_token)
curl -v -s -k -H "Authorization: bearer $UAA_TOKEN" "https://$BOSH_HOST:25555/deployments"
```
This commands run without errors.

So I imply that the problem is on turblulence side.

**Comment by cppforlife** [comment]
what are the scopes in that token?

**Comment by allomov** [comment]
I user `director` client which has the following uaa props:
```
→ uaac clients | grep -A 9 director
  director
    scope: uaa.none
    resource_ids: none
    authorized_grant_types: client_credentials
    autoapprove:
    access_token_validity: 600
    refresh_token_validity: 86400
    action: none
    authorities: bosh.admin
    lastmodified: 1484350095257
```
The thing is that UAA can return token with correct scope for this client if you use golang `bosh-cli` or `curl`, but not if you fetch the token from `turbulence` code.

**Comment by cppforlife** [comment]
@allomov looks like client was adding basic auth which seems to trip up director.

**Comment by allomov** [comment]
Thank you for this fix. This might work.

**Comment by allomov** [comment]
I really appreciate how fast you can deliver a new release. Is bosh cli the only tool you use to do it? Could you tell what are using to update bosh.io?

**Comment by allomov** [comment]
I gave a try to this changes (with release 0.6), but I got an error that might be related to how release is built. The error says:
```
17:50:24 | Preparing deployment: Preparing deployment (00:00:00)
17:50:24 | Preparing package compilation: Finding packages to compile (00:00:00)
17:50:24 | Compiling packages: golang/e462f9e7f4577234a96fa1e72e752c758d5f720e

 (00:01:00)
            L Error: photon: HTTP 504: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```
That might be an infrastructure problem, at the same time it can appear that golang package is not uploaded to a blobstore.

Will investigate it later today.

**Comment by cppforlife** [comment]
thats a photon cpi (im assuming you are using photon) problem i believe.

**Comment by cppforlife** [comment]
not sure what you mean by "update bosh.io". bosh.io just looks like at final releases that were published in the github repo.

**Comment by allomov** [comment]
Yes, I use photon here. It might be an infrastructure problem.

The answer about bosh.io is what I was looking for. I thought it can use some triggers like github releases or tags (that have only v0.5 right now), but now I understand it is enough to look for a final release in the repo.

Thank you.
