### ISSUE TITLE
You shouldn't be using pid_utils with a script name of 'ctl'

### ISSUE THREAD

**Issue by voelzmo** [cppforlife/turbulence-release#7]
[pid_utils](https://github.com/cppforlife/turbulence-release/blob/master/src/pid_utils.sh#L1-L5) redirects the output to `/var/vcap/monit/<script_name>.{out,err}.log`, so if other releases do the same thing, everything ends up in one logfile.

Probably you should either:
- name the logfile after the job's name, not the script's name
- include the job's name in the script's name, like e.g. cf-release or concourse do

**Comment by cppforlife** [comment]
Removed pid_utils entirely.
