### ISSUE TITLE
"firewall" BlockBOSHAgent description isn't clear

### ISSUE THREAD

**Issue by kkallday** [cppforlife/turbulence-release#9]
Hi,

The description of the `BlockBOSHAgent` [1] boolean for `firewall` incidents seem to be contradictory. It says:

```
set BlockBOSHAgent (bool) to false to block access to the BOSH Agent
```

It seems like you would want to say:

```
set BlockBOSHAgent (bool) to true to block access to the BOSH Agent
```

Given `BlockBOSHAgent` is set to `false` by default. 

[1] https://github.com/cppforlife/turbulence-release/blob/master/docs/api.md#firewall

**Comment by cppforlife** [comment]
Updated.
